# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'LearnSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.2'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'ObjectMapper'
  pod 'Moya'
  pod 'SwiftyJSON'
 # pod 'RxAlamofire'

  # Pods for LearnSwift

end
